# Generated by Django 4.2.1 on 2023-05-10 18:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('cpf', models.CharField(max_length=11)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
