# Generated by Django 4.2.1 on 2023-05-10 19:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('BankInvest_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacoes',
            fields=[
                ('id_transacoes', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao', models.TextField(null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data', models.DateTimeField(auto_now=True)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BankInvest_app.cliente')),
            ],
        ),
    ]
