# Generated by Django 4.2.1 on 2023-05-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankInvest_app', '0003_cliente_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.TextField(default='gabrielpimentelsenai22@gmail.com'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sobreNome',
            field=models.TextField(default='Pimentel'),
        ),
    ]
