# Generated by Django 4.2.1 on 2023-05-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankInvest_app', '0004_cliente_email_cliente_sobrenome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='image',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='senha',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sobreNome',
            field=models.TextField(),
        ),
    ]
