# Generated by Django 4.2.1 on 2023-05-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankInvest_app', '0005_remove_cliente_image_alter_cliente_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='clientes/'),
        ),
    ]
