# Generated by Django 4.2.1 on 2023-05-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankInvest_app', '0006_cliente_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacoes',
            name='saldo',
        ),
        migrations.AddField(
            model_name='cliente',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
    ]
