# Generated by Django 4.2.1 on 2023-05-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankInvest_app', '0007_remove_transacoes_saldo_cliente_saldo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='imagem',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='saldo',
            field=models.FloatField(),
        ),
    ]
